name: Main

on:
  push:
    branches:
     - "**"
  pull_request:
    branches:
     - "**"
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update dependencies
        run: bash update_dependencies.sh

      - name: Build
        run: bash build_pack_test.sh
        
      - uses: actions/upload-artifact@v2
        with:
          path: dist/Sonic4ModLoader.7z

      - uses: actions/upload-artifact@v2
        with:
          path: dist/Sonic4ModLoader_7zip-less.7z

      - uses: actions/upload-artifact@v2
        with:
          path: dist/SHA256SUMS

      - uses: actions/upload-artifact@v2
        with:
          path: dist/Sonic4ModLoader/AMBPatcher.exe
