name: Midday build rs

on:
  push:
    branches:
     - "**"
  pull_request:
    branches:
     - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-pack-win64-rs:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - run: py -3.12 -m pip install --user pipx
      - run: py -3.12 -m pipx ensurepath
      - run: pipx install gvsbuild
      - run: gvsbuild build gtk4
      - run: echo "C:\gtk-build\gtk\x64\release\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Update dependencies
        run: bash update_dependencies.sh

      - name: Build
        run: cargo build --verbose
        
      - uses: actions/upload-artifact@v2
        with:
          name: Sonic 4 Mod Loader
          path: dist/Sonic4ModLoader.7z

      - uses: actions/upload-artifact@v2
        with:
          name: Sonic 4 Mod Loader (without 7-Zip)
          path: dist/Sonic4ModLoader_7zip-less.7z

      - uses: actions/upload-artifact@v2
        with:
          name: SHA256 sums
          path: dist/SHA256SUMS

      - uses: actions/upload-artifact@v2
        with:
          name: AMBPatcher
          path: dist/Sonic4ModLoader/AMBPatcher.exe