name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        python3 fix_sh_newline.py
        bash update_dependencies.sh
        bash build_pack.sh
    
    - name: Upload Sonic4ModLoader.7z
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Sonic4ModLoader.7z
        path: dist/Sonic4ModLoader.7z

    - name: Upload Sonic4ModLoader_7zip-less.7z
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Sonic4ModLoader_7zip-less.7z
        path: dist/Sonic4ModLoader_7zip-less.7z

    - name: Upload AMBPatcher
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AMBPatcher.exe
        path: dist/Sonic4ModLoader/AMBPatcher.exe

    - name: Upload SHA256SUMS
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SHA256SUMS
        path: dist/SHA256SUMS
