name: Midday build

on:
  push:
    branches:
     - "**"
  pull_request:
    branches:
     - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v2

  dependencies:
    needs: checkout
    runs-on: windows-latest
    steps:
      - name: Update dependencies
        run: bash update_dependencies.sh

  build:
    needs: checkout
    runs-on: windows-latest
    steps:
      - name: Build
        run: bash build_pack_test.sh
        
  artifacts:
    needs: [build, dependencies]
    runs-on: windows-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: Sonic 4 Mod Loader
          path: dist/Sonic4ModLoader.7z

      - uses: actions/upload-artifact@v2
        with:
          name: Sonic 4 Mod Loader (without 7-Zip)
          path: dist/Sonic4ModLoader_7zip-less.7z

      - uses: actions/upload-artifact@v2
        with:
          name: SHA256 sums
          path: dist/SHA256SUMS

      - uses: actions/upload-artifact@v2
        with:
          name: AMBPatcher
          path: dist/Sonic4ModLoader/AMBPatcher.exe
  
  tests:
    needs: [build, dependencies]
    runs-on: windows-latest
    steps:
      - name: Tests
        run: bash ./tests/run_tests.sh --no-crash