name: Release

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-pack-win64:
    runs-on: windows-2022
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - run: py -3.12 -m pip install --user pipx
      - run: py -3.12 -m pipx ensurepath
      - run: pipx install gvsbuild
      # Remove when fixed https://github.com/wingtk/gvsbuild/issues/1436#issuecomment-2424106992
      - run: |
          py -m venv .venv
          .\.venv\Scripts\activate.ps1
          py -m pip install gvsbuild
          gvsbuild build gtk4 libadwaita librsvg
      # - run: gvsbuild build gtk4 libadwaita librsvg
      - run: echo "C:\gtk-build\gtk\x64\release\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Update dependencies
        run: bash update_dependencies.sh

      - name: Build .Net
        run: bash build.sh

      - name: Build Rust
        run: cargo build --release

      - name: Pack
        run: bash pack.sh
        
      - uses: actions/upload-artifact@v4
        with:
          name: Sonic 4 Mod Loader
          path: dist/Sonic4ModLoader.zip

      - uses: actions/upload-artifact@v4
        with:
          name: SHA256 sums
          path: dist/SHA256SUMS

      - uses: actions/upload-artifact@v4
        with:
          name: AMBPatcher
          path: dist/Sonic4ModLoader/AMBPatcher.exe
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v2

      - name: Build AMBPatcher
        run: |
          dotnet publish Sonic4_ModLoader/AMBPatcher -c Release --os linux
          mkdir -p "./dist/Sonic4ModLoader/Mod Loader - licenses"
          cp "./Sonic4_ModLoader/AMBPatcher/bin/Release/net6.0/linux-x64/publish/AMBPatcher" "./dist/Sonic4ModLoader/AMBPatcher.exe"

      - name: Run tests
        run: bash ./tests/run_tests.sh --no-crash